spring:
  application:
    name: cfd-reporting-service
  cloud:
    nacos:
      discovery:
        enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:cfd_reporting}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8089
