spring:
  application:
    name: cfd-order-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/cfd_order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  cloud:
    nacos:
      discovery:
        enabled: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

services:
  risk:
    url: http://localhost:8081

cfd:
  topic:
    orderOpen: cfd.order.open.command
    tradeFeedback: cfd.trade.opened.feedback
  outbox:
    relay:
      fixed-delay-ms: 1000
      batch-size: 200

server:
  port: 8082
