spring:
  application:
    name: cfd-backend-management-service
  cloud:
    nacos:
      discovery:
        enabled: false
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cfd_backend?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8091
